import Head from 'next/head';
import { ReactElement } from 'react';
import Layout from '../components/layout';
import { useAuth } from '../context/auth';
import styles from '../styles/Home.module.css';
import { NextPageWithLayout } from './_app';
import { Post } from '../types/post';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { adminDB } from '../firebase/server';
import PostItemCard from '../components/post-item-card';

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async (
  conetxt,
) => {
  // postの単体を取得するときはdoc。post全てを取得するときはcollection

  const snap = await adminDB
    .collection('posts')
    .orderBy('createdAt', 'desc')
    .limit(20)
    .get();

  const posts = snap.docs.map((doc) => doc.data() as Post);
  return {
    props: {
      posts,
    },
  };
};

const Home: NextPageWithLayout<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
  const { user } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h2>最新の記事</h2>
        {posts.length ? (
          <ul className="space-y-5 mt-6">
            {posts?.map((post) => (
              <li key={post.id}>
                <PostItemCard post={post} />
              </li>
            ))}
          </ul>
        ) : (
          <p>記事がありません</p>
        )}
      </main>
    </div>
  );
};
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
export default Home;
